version: '3.8'
services:
  web:
    build: ./docker/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d